name: Build and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build Project
        run: npm run build
        working-directory: ./frontend

      - name: List build directory contents
        run: ls -l build
        working-directory: ./frontend

      - name: Copy build artifacts to production branch
        run: |
          git fetch --all
          # Check if the production branch exists on the remote
          if git rev-parse --verify origin/production; then
            git checkout production
            git reset --hard origin/production
          else
            git checkout --orphan production
            git rm -rf .
          fi
          # Copy the build files from the build directory
          cp -a ${GITHUB_WORKSPACE}/frontend/build/* .
          # If there were changes (new files), then commit them
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Deploy production build"
            git push origin production --force
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


