name: Build and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Change to Frontend Directory
        run: cd frontend

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build Project
        run: npm run build
        working-directory: ./frontend

      - name: List build directory contents # Debugging step to list contents of the build directory
        run: ls -l
        working-directory: ./frontend/build



      - name: Deploy to Production
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch --all
          git checkout production || git checkout --orphan production
          git reset --hard origin/production
          git rm -rf * # Clear out the current contents
          cp -a ../build/. . # Copy everything from the build directory
          git add .
          git commit -m "Production Build" || echo "No changes to commit"
          git push origin production --force
        working-directory: ./frontend/build
      

        
